(define (problem RoversSuministrosPersonal) (:domain BasesMarte_extension1)

    (:objects
        rover0 rover1 - rover
        p0 p1 p2 p3 p4 p5 p6 p7 p8 p9 - personal
        s0 s1 s2 s3 s4 s5 s6 s7 s8 s9 s10 s11 s12 s13 s14 s15 s16 s17 s18 s19 - suministro
        al2 - almacen
        as1 as3 as4 - asentamiento
    )

    (:init
        (= (p) 2)
        (= (s) 1)
        (conectado as1 al2)
        (conectado al2 as1)
        (conectado al2 as3)
        (conectado as3 al2)
        (conectado as3 as4)
        (conectado as4 as3)
        (aparcado rover0 as1)
        (= (PersonalCargado rover0) 0)
        (= (SuministroCargado rover0) 0)
        (aparcado rover1 as1)
        (= (PersonalCargado rover1) 0)
        (= (SuministroCargado rover1) 0)
        (en_base p0 as3)
        (pedido p0 as1)
        (en_base p1 as4)
        (pedido p1 as1)
        (en_base p2 as4)
        (pedido p2 as1)
        (en_base p3 as3)
        (pedido p3 as1)
        (en_base p4 as1)
        (pedido p4 as4)
        (en_base p5 as4)
        (pedido p5 as1)
        (en_base p6 as4)
        (pedido p6 as3)
        (en_base p7 as1)
        (pedido p7 as3)
        (en_base p8 as3)
        (pedido p8 as1)
        (en_base p9 as4)
        (pedido p9 as3)
        (en_base s0 al2)
        (pedido s0 as4)
        (en_base s1 al2)
        (pedido s1 as4)
        (en_base s2 al2)
        (pedido s2 as4)
        (en_base s3 al2)
        (pedido s3 as1)
        (en_base s4 al2)
        (pedido s4 as3)
        (en_base s5 al2)
        (pedido s5 as1)
        (en_base s6 al2)
        (pedido s6 as3)
        (en_base s7 al2)
        (pedido s7 as3)
        (en_base s8 al2)
        (pedido s8 as4)
        (en_base s9 al2)
        (pedido s9 as4)
        (en_base s10 al2)
        (pedido s10 as3)
        (en_base s11 al2)
        (pedido s11 as1)
        (en_base s12 al2)
        (pedido s12 as4)
        (en_base s13 al2)
        (pedido s13 as1)
        (en_base s14 al2)
        (pedido s14 as4)
        (en_base s15 al2)
        (pedido s15 as4)
        (en_base s16 al2)
        (pedido s16 as3)
        (en_base s17 al2)
        (pedido s17 as1)
        (en_base s18 al2)
        (pedido s18 as3)
        (en_base s19 al2)
        (pedido s19 as4)
    )

    (:goal (forall (?t - transportable) (suministrado ?t)))

)
