(define (problem RoversSuministrosPersonal) (:domain BasesMarte_extension2)

    (:objects
        rover0 rover1 - rover
        p0 p1 p2 p3 p4 p5 p6 p7 p8 p9 - personal
        s0 s1 s2 s3 s4 s5 s6 s7 s8 s9 - suministro
        al1 al2 al5 al6 - almacen
        as3 as4 - asentamiento
    )

    (:init
        (= (p) 2)
        (= (s) 1)
        (= (CombustibleTotal) 0)
        (= (DecrecimientoCombusitible) 0)
        (conectado al1 al2)
        (conectado al2 al1)
        (conectado al2 as3)
        (conectado as3 al2)
        (conectado al1 as3)
        (conectado as3 al1)
        (conectado as3 as4)
        (conectado as4 as3)
        (conectado as4 al5)
        (conectado al5 as4)
        (conectado as4 al6)
        (conectado al6 as4)
        (conectado al5 al6)
        (conectado al6 al5)
        (aparcado rover0 as3)
        (= (PersonalCargado rover0) 0)
        (= (SuministroCargado rover0) 0)
        (= (CombustibleRestante rover0) 10000)
        (aparcado rover1 as4)
        (= (PersonalCargado rover1) 0)
        (= (SuministroCargado rover1) 0)
        (= (CombustibleRestante rover1) 10000)
        (en_base p0 as4)
        (pedido p0 as3)
        (en_base p1 as4)
        (pedido p1 as3)
        (en_base p2 as3)
        (pedido p2 as4)
        (en_base p3 as3)
        (pedido p3 as4)
        (en_base p4 as4)
        (pedido p4 as3)
        (en_base p5 as3)
        (pedido p5 as4)
        (en_base p6 as3)
        (pedido p6 as4)
        (en_base p7 as3)
        (pedido p7 as4)
        (en_base p8 as4)
        (pedido p8 as3)
        (en_base p9 as3)
        (pedido p9 as4)
        (en_base s0 al5)
        (pedido s0 as3)
        (en_base s1 al6)
        (pedido s1 as4)
        (en_base s2 al5)
        (pedido s2 as3)
        (en_base s3 al1)
        (pedido s3 as3)
        (en_base s4 al2)
        (pedido s4 as4)
        (en_base s5 al1)
        (pedido s5 as3)
        (en_base s6 al5)
        (pedido s6 as3)
        (en_base s7 al1)
        (pedido s7 as3)
        (en_base s8 al1)
        (pedido s8 as3)
        (en_base s9 al6)
        (pedido s9 as3)
    )

    (:goal (forall (?t - transportable) (suministrado ?t)))

)
